#ifndef myoptions_h
#define myoptions_h

/* Generated by myoptions.h generator - v0.8.1 */
/* https://e2002.github.io/docs/myoptions-generator.html?r=71,1,2,4,8,73,41,43,54,55&i=1,2,3,4,15,16,17,28,29,30,31,32,33&v=4,5,-1,255,27,26,25,36,34,39,35,33,32 */
/* Put this file next to yoRadio.ino and restart Arduino IDE. */

/* !!! Attention !!! */
/* This configuration depends on some additional libraries. Please install them using the library manager: */
/* Adafruit GFX Library, OneButton */

/* !!! Do not be alarmed, all right, the default values ​​are not included in this file !!! */
//#define L10N_LANGUAGE      EN
#define L10N_LANGUAGE			RU

#define DSP_MODEL			DSP_SSD1322

#define SSD1322_GRAYSCALE         true

#define ENC2_BTNR			33
#define ENC2_BTNL			35
#define ENC2_BTNB			32
#define ENC2_INTERNALPULLUP       false

#define ENC_BTNR			34
#define ENC_BTNL			36
#define ENC_BTNB			39
#define ENC_INTERNALPULLUP        false

#define SDC_CS			  21
#define IR_PIN        15
#define BITRATE_FULL  true

//#define EXT_WEATHER false

#endif